version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Azure.WebJobs
    versions:
    - 3.0.25
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
